nowcasting_forecast/database/models.py, nowcasting_forecast/database/utils.py, tests/database/test_read.py, tests/database/test_utils.py, tests/test_app.py
add timezone to sqlalcmy models
=> add timezones

nowcasting_forecast/app.py, nowcasting_forecast/database/fake.py, nowcasting_forecast/database/models.py, nowcasting_forecast/database/read.py, tests/database/test_fake.py, tests/database/test_read.py, tests/test_app.py
- add national forecasts (fake)
- add read national forecasts 
- add national forecast to app
add extra tests to check forecasts are made
=> add fake and read function for latest

nowcasting_forecast/models/nwp_solar_simple.py
Change nwp simple model to produce time dependent forecasts , and different from each example
Fixes #17 
add unittests
ran locally
=> make mwp simple model give 2 hours forecast

nowcasting_forecast/database/national.py, tests/database/test_national.py
=> Make national forecast return sql object

nowcasting_forecast/database/read.py, nowcasting_forecast/models/nwp_solar_simple.py, tests/models/test_nwp_simple.py
read location rather than making a new one each time
Fixes #15 
normal unittests
=> read location from database

nowcasting_forecast/database/read.py
=> remove un needed function input

nowcasting_forecast/models/nwp_solar_simple.py
Fix for finding gsp location from metadata
normal unitests
ran service locally
=> fix gsp location

nowcasting_forecast/models/nwp_solar_simple.py
Only make once input data object
normal unittests
=> only make input data object once fore each forecast

nowcasting_forecast/database/national.py, nowcasting_forecast/models/nwp_solar_simple.py
_Please delete the italicised instruction text!
Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. List any dependencies that are required for this change._
Fixes #
=> use id from metadata

nowcasting_forecast/database/national.py, nowcasting_forecast/models/nwp_solar_simple.py, tests/models/test_nwp_simple.py, tests/test_app.py
Keep forecast as sql object, so that locations dont get repeated
normal unittests + run skipped tests
=> Fix locations

.bumpversion.cfg, nowcasting_forecast/__init__.py, nowcasting_forecast/app.py, nowcasting_forecast/batch.py, nowcasting_forecast/models/nwp_solar_simple.py, setup.py
=> move version to __init__ file, and add logging

nowcasting_forecast/database/models.py, nowcasting_forecast/models/nwp_solar_simple.py, setup.py
speed up sql query
- add index on gsp
- add indexes on all foreign keys
=> Speed up gsp

nowcasting_forecast/models/nwp_simple_trained/nwp_simple_trained.py, nowcasting_forecast/models/nwp_solar_simple.py, requirements.txt, tests/conftest.py
update to datamodel 0.0.22
#46
normal unittests
=> nowcasting_datamodel==0.0.22

nowcasting_forecast/app.py, nowcasting_forecast/models/nwp_simple_trained/nwp_simple_trained.py, nowcasting_forecast/models/nwp_solar_simple.py
=> add option LOGLEVEL

nowcasting_forecast/config/mvp_v0.yaml, nowcasting_forecast/config/mvp_v1.yaml, requirements.txt, test-docker-compose.yml, tests/conftest.py
Update nowcasting dataset and datamodel\
normal unittest
=> update nowcastin_dataset, and nowcasting_datamodel

nowcasting_forecast/batch.py, nowcasting_forecast/config/mvp_v2.yaml, test-docker-compose.yml, tests/conftest.py, tests/test_batch.py
add pv data to mvp_v2 config
- unittest
- added unittests
@jacobbieker I was thinking we merge this and you PR #56 and then run it locally to see what happens. We probably have to wait for the satellite consumer to get back online for that though
=> Pv ingest2

requirements.txt
=> nowcasting_datamodel==0.0.50

nowcasting_forecast/app.py, requirements.txt, tests/conftest.py, tests/test_app.py
Update to datamodel 0.0.51
TDD added failing test first, then got it working
=> Update datamodle 0.0.50

requirements.txt
upgrade to data model 0.0.53
Fixes #66 
=> nowcasting_datamodel==0.0.53

nowcasting_forecast/app.py, nowcasting_forecast/config/mvp_v2.yaml, requirements.txt
update to nowcasting_dataset==3.3.11
Fixes #
=> update nowcasting_dataset, update hrv satellite pixels

requirements.txt
Update nowcasting_dataset to 3.3.12
Fixes #
update nowcasting_dataset, fix for loading satellite data into memory
=> update dataset to 3.3.12

infrastructure/docker/Dockerfile, nowcasting_forecast/app.py, nowcasting_forecast/models/cnn/dataloader.py, tests/models/cnn/test_cnn_dataloader.py
fix for batch
add logging
Fixes #
=> Fix batch location

nowcasting_forecast/app.py, nowcasting_forecast/batch.py, requirements.txt, tests/test_app.py
Save first batch to s3
Fixes #59 
normal unittests
TODO: add to test_app
=> save first batch to s3, option with BATCH_SAVE_DIR

nowcasting_forecast/app.py, nowcasting_forecast/models/cnn/dataloader.py, requirements.txt
Adds saving out the BatchML dictionary to a location for the first batch, so that it can be used for debugging/visualization
Fixes #59 
=> Add saving out BatchML batch

nowcasting_forecast/app.py
=> save to /batch when making batches

nowcasting_forecast/models/cnn/cnn.py, nowcasting_forecast/models/utils.py
Fixes #81
The HF model was being loaded, but not replacing the uninitialized model, so was giving incorrect predictions.
Fixes #
=> Fix HuggingFace Model not actaully being loaded

nowcasting_forecast/app.py, requirements.txt, tests/conftest.py
update nowcasting_dataset, so pv data is normalized correctly
Fixes #97 
unittests
=> nowcasting_dataset==3.3.20

nowcasting_forecast/models/sun.py, requirements.txt
upgrade to nowcastingD_ata 3.3.22
Fixes #88 
unittests
=> nowcasting_dataset==3.3.22

requirements.txt, tests/test_batch.py
update nowcasting_dataset
add test to check gsp times
Fixes #114 
unittests, + added tests
=> Fix gsp data

README.md, nowcasting_forecast/config/mvp_v2.yaml, requirements.txt
use linear interpolation on pv data
Fixes #
- ran locally
- ran unitests
=> nowcasting_dataset==3.5.5

nowcasting_forecast/config/mvp_v2.yaml
add env to config
will need to add ENV to infrastructure
Fixes #
unittests
=> add ENVIRONMENT to default

.pre-commit-config.yaml, nowcasting_forecast/config/mvp_v2.yaml, requirements.txt
update dataset
mvp_v2 - only use pvoutput.org
Fixes #
=> update dataset 3.5.12

.gitignore, README.md, environment.yml
Simple PR. Just adding an `environment.yml` so I can install with `conda`. I couldn't get it to install using `pip` on my local machine for some reason.
Installs locally.
Tests pass.
=> Add conda environment.yml

requirements.txt, tests/conftest.py
Update dataset to 3.6.1. This create the corretc shape of pv data in the night
Fixes #122 
=> nowcasting_dataset==3.6.1

requirements.txt
=> nowcasting_dataset==3.6.3

nowcasting_forecast/models/cnn/model.py
Fix for model to use gsp data, not pv
Fixes #
Normal CI
=> fix use gsp data

nowcasting_forecast/models/cnn/model.py
remove gsp embedding set to 1.
This will help #154 . But needs to be removed once #155 is done
Fixes #
CI testing
=> remove gsp embedding

requirements.txt
fix: update datamodel to save gsp 317 aswell
Fixes #
=> udpate to nowcasting_datamodel==1.1.27

requirements.txt, tests/conftest.py
upgrade to dm 1.1.36 which include forecast partition
CI tests
=> upgrade to dm 1.1.36

nowcasting_forecast/models/cnn/model.py, nowcasting_forecast/models/cnn/readme.md
Upgrade PVnet to use new GSP data
Fixes #
CI tests
=> update to model v5, neptune run 1197

requirements.txt, tests/conftest.py, tests/models/test_sun.py
Update dm, this speeds up the forecast update process
Fixes #
Run normal test in CI
=> nowcasting_datamodel==1.1.40

requirements.txt
upgrade dataset so that the satellite consumer still works if there is not 5 min latest file
Fixes #
CI tests
=> nowcasting_dataset==3.7.15

README.md, requirements.txt
update to new datamodel, model_id gets saved
Ci tests
=> nowcasting_datamodel==1.2.1

requirements.txt
Update to new data model, saving model is in latest table
Fixes #
=> nowcasting_datamodel==1.2.4

requirements.txt
Update to nowcasting_datamodel==1.2.5
Fixes #
CI tests
=> nowcasting_datamodel==1.2.5

requirements.txt, tests/conftest.py
update datamodel 1.3.3. Load adjuster mode name specific results
Fixes #
CI tests
=> nowcasting_datamodel==1.3.3

requirements.txt
upgrade to dm, so saves to `forecast_value_latest` table
Fixes #
=> nowcasting_datamodel==1.3.9

requirements.txt
Update to dm 1.3.10, fix for saving to forecat_value_latest
Fixes #
CI test
=> nowcasting_datamodel==1.3.10

infrastructure/docker/Dockerfile, nowcasting_forecast/batch.py, requirements.txt
upgrade dm - fix for adjuster
CI test
=> nowcasting_datamodel==1.4.0

nowcasting_forecast/models/cnn/cnn.py
=> removing timing fix,

infrastructure/docker/Dockerfile
use full torch in docker file
CI tests
=> use full torch in docker file

requirements.txt
Upgrade datamodel
Helps with https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/263
CI tests
=> nowcasting_datamodel==1.5.8
